name: manachyna_kusa
description: Aplicación móvil multiservicio para la gestión y solicitud de servicios domésticos a domicilio en el cantón Tena, provincia de Napo.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  provider: ^6.0.5
  intl: ^0.18.1
  image_picker: ^1.0.2
  cached_network_image: ^3.2.3
  geolocator: ^10.0.0
  google_maps_flutter: ^2.4.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
